server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # try files, fallback to index.html for SPA routes
  location / {
    try_files $uri $uri/ /index.html;
  }

  # cache static assets
  location ~* \.(?:css|js|json|xml|svg|jpg|jpeg|png|gif|ico|woff2?)$ {
    try_files $uri =404;
    expires 30d;
    access_log off;
  }

  gzip on;
  gzip_types text/plain application/javascript text/css application/json image/svg+xml;
}
